package com.example.i_o_spring_project.authority;

public enum Authorities {
	ADD_COMPANY, UPDATE_COMPANY, REMOVE_COMPANY, GET_ALL_COMPANIES, GET_COMPANY, ADD_CUSTOMER, UPDATE_CUSTOMER,
	REMOVE_CUSTOMER, GET_ALL_CUSTOMERS, GET_CUSTOMER, ADD_COUPON, UPDATE_COUPON, DELETE_COUPON, GET_COUPON, GET_COUPONS,
	PURCHASE_COUPON, REMOVE_PURCHASED_COUPON;

}
